blueprint:
  name: Exhaust Fan - Auto On/Off (Humidity + Optional Rate/Timer/Latch)
  description: >
    Turns an exhaust fan ON when humidity is rising (via optional humidity_rate sensor)
    OR falls back to humidity threshold if no rate sensor is provided. Turns fan OFF
    when humidity normalizes, optionally using a latch boolean (shower_mode), sleep-hours
    inhibit, and a max runtime timer.

    CHANGE: shower_mode_boolean is always set ON/OFF when the start/stop logic is satisfied
    (detection), even if sleep-hours inhibit prevents turning the fan on/off (actuation).

  domain: automation
  source_url: https://raw.githubusercontent.com/pickerin/HA_Blueprints/main/Automations/exhaust_fan_humidity_rise_auto_on_off.yaml
  input:
    fan_switch:
      name: Exhaust fan switch
      selector:
        entity:
          domain: [switch]
    humidity_sensor:
      name: Humidity sensor (%)
      selector:
        entity:
          domain: [sensor]
    humidity_rate_sensor:
      name: Humidity rate sensor (optional)
      description: >
        Optional derivative sensor like sensor.<room>_humidity_rate. If omitted, the
        automation falls back to humidity thresholds.
      default: ""
      selector:
        entity:
          domain: [sensor]
    sleep_hours_boolean:
      name: Sleep hours inhibit boolean (optional)
      description: >
        If provided and ON, the automation will not actuate the fan (turn on/off),
        but it will still set/clear the latch for debugging.
      default: ""
      selector:
        entity:
          domain: [input_boolean]
    shower_mode_boolean:
      name: Latch boolean / shower_mode (optional)
      description: >
        If provided, the automation will set it ON when the start logic is satisfied,
        and set it OFF when the stop logic is satisfied. Fan actuation is separately
        gated by sleep-hours inhibit.
      default: ""
      selector:
        entity:
          domain: [input_boolean]
    max_run_timer:
      name: Max runtime timer (optional)
      description: >
        If provided, starts the timer when fan is turned on. When timer finishes,
        fan is turned off and latch cleared.
      default: ""
      selector:
        entity:
          domain: [timer]

    rate_on_threshold:
      name: Rate ON threshold
      description: Turn ON when humidity_rate > this value (and humidity above min).
      default: 0.35
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.01
          mode: box
    rate_on_for:
      name: Rate ON must hold for
      default:
        hours: 0
        minutes: 2
        seconds: 0
      selector:
        duration: {}
    humidity_min_to_start:
      name: Minimum humidity to allow start (rate mode)
      default: 45
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: box

    rate_off_threshold:
      name: Rate OFF threshold
      description: Turn OFF when humidity_rate < this value (and humidity below max).
      default: 0.05
      selector:
        number:
          min: 0.0
          max: 5.0
          step: 0.01
          mode: box
    rate_off_for:
      name: Rate OFF must hold for
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration: {}
    humidity_max_to_stop:
      name: Maximum humidity to allow stop (rate mode)
      default: 60
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: box

    humidity_on_threshold:
      name: Humidity ON threshold (fallback)
      description: If no rate sensor, turn ON when humidity > this threshold.
      default: 55
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: box
    humidity_on_for:
      name: Humidity ON must hold for (fallback)
      default:
        hours: 0
        minutes: 2
        seconds: 0
      selector:
        duration: {}

    humidity_off_threshold:
      name: Humidity OFF threshold (fallback)
      description: If no rate sensor, turn OFF when humidity < this threshold.
      default: 50
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 1.0
          mode: box
    humidity_off_for:
      name: Humidity OFF must hold for (fallback)
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration: {}

mode: single

variables:
  fan: !input fan_switch
  hum: !input humidity_sensor
  rate: !input humidity_rate_sensor
  sleep: !input sleep_hours_boolean
  latch: !input shower_mode_boolean
  max_timer: !input max_run_timer

  rate_on: !input rate_on_threshold
  hum_min_start: !input humidity_min_to_start
  rate_off: !input rate_off_threshold
  hum_max_stop: !input humidity_max_to_stop
  hum_on: !input humidity_on_threshold
  hum_off: !input humidity_off_threshold

  # NEW: common "can actuate fan" gate (sleep must be off, or not provided)
  can_actuate: "{{ sleep == '' or is_state(sleep, 'off') }}"

triggers:
  # CHANGE: removed sleep gating from *detection* triggers
  - trigger: template
    id: start_rate
    value_template: >-
      {{ rate != ''
         and states[rate] is not none
         and (states[rate].state | float(0)) > (rate_on | float(0))
         and states[hum] is not none
         and (states[hum].state  | float(0)) > (hum_min_start | float(0)) }}
    for: !input rate_on_for

  - trigger: template
    id: start_humidity
    value_template: >-
      {{ rate == ''
         and states[hum] is not none
         and (states[hum].state | float(0)) > (hum_on | float(0)) }}
    for: !input humidity_on_for

  # Stop triggers remain latch-protected (avoids turning off manually-run fan),
  # but sleep does not block "debug latch clear"
  - trigger: template
    id: stop_rate
    value_template: >-
      {{ rate != ''
         and (latch == '' or is_state(latch, 'on'))
         and states[rate] is not none
         and (states[rate].state | float(0)) < (rate_off | float(0))
         and states[hum] is not none
         and (states[hum].state  | float(0)) < (hum_max_stop | float(0)) }}
    for: !input rate_off_for

  - trigger: template
    id: stop_humidity
    value_template: >-
      {{ rate == ''
         and (latch == '' or is_state(latch, 'on'))
         and states[hum] is not none
         and (states[hum].state | float(0)) < (hum_off | float(0)) }}
    for: !input humidity_off_for

  - trigger: event
    id: timer_finished
    event_type: timer.finished

conditions: []

actions:
  - choose:

      # START PATH
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['start_rate', 'start_humidity'] }}"
        sequence:

          # Always set latch ON as debug signal (if provided)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ latch != '' }}"
                sequence:
                  - action: input_boolean.turn_on
                    target:
                      entity_id: "{{ latch }}"

          # Actuate fan + timer only if allowed (sleep off / not provided)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ can_actuate }}"
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: "{{ fan }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ max_timer != '' }}"
                        sequence:
                          - action: timer.start
                            target:
                              entity_id: "{{ max_timer }}"

      # STOP PATH
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['stop_rate', 'stop_humidity'] }}"
        sequence:

          # Actuate fan off + cancel timer only if allowed (sleep off / not provided)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ can_actuate }}"
                sequence:
                  - action: switch.turn_off
                    target:
                      entity_id: "{{ fan }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ max_timer != '' }}"
                        sequence:
                          - action: timer.cancel
                            target:
                              entity_id: "{{ max_timer }}"

          # Always clear latch OFF as debug signal (if provided)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ latch != '' }}"
                sequence:
                  - action: input_boolean.turn_off
                    target:
                      entity_id: "{{ latch }}"

      # TIMER FINISHED PATH (safety: still turns off regardless)
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.id == 'timer_finished'
                 and max_timer != ''
                 and trigger.event.data.entity_id == max_timer }}
        sequence:
          - action: switch.turn_off
            target:
              entity_id: "{{ fan }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ latch != '' }}"
                sequence:
                  - action: input_boolean.turn_off
                    target:
                      entity_id: "{{ latch }}"